package org.fotm.java17.record;

import java.math.BigDecimal;
import java.util.Comparator;
import java.util.stream.Stream;

public record NoodlingRecord(String name, BigDecimal price, String purpose) {


    /*
    To apply validation, create a CODE block; NOT a constructor.
     */
    public NoodlingRecord {
        if (name == null || name.isBlank())
            throw new IllegalArgumentException("name is required");
        if (price.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException("price must be positive");
        }

    }

    /*
    The autogenerated constructor is called the canonical constructor.
    Any constructor you create must call the canonical constructor.
     */
    public NoodlingRecord(String name, BigDecimal price) {
        this(name, price, "default value");
    }

    public static void spewSorted(NoodlingRecord... records) {

        Stream.of(records)
              .sorted(Comparator.comparing(NoodlingRecord::name))
              .forEach(System.out::println);
    }
}
